<?php

namespace App\Http\Controllers;

use Facebook\Facebook;
use App\Traits\ApiResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class FacebookController extends Controller
{
    use ApiResponse;
    public function createPost(Request $request)
    {
        $fb = new Facebook([
            'app_id' => config('app.facebook_app_id'),
            'app_secret' => config('app.facebook_app_secret'),
            'default_graph_version' => config('app.facebook_default_graph_version'),
        ]);

        $key = config('app.facebook_app_id');
        $scret = config('app.facebook_app_secret');
        $accessToken = $this->get_access_token($key, $scret);
        // $accessToken = "EAAC8B73OSYgBALHtmfM7sSR5iYY1eOJDEZBLdKPnZCEZBHLvZB6dlFXLEd00cMUzUMUJh2VccswtIWgS4aRw6pm5xfqD4hqrCSRPwWfIzGh13wWJ1MiOLTl6YhzApZAoERPPyIjzI1M5razzON4Kt4qnAOYoHHMZAQZBz5a3dzxCgZDZD";
        $graphVersion = config('app.facebook_default_graph_version');

        $data = [
            'message' => request()->message,
        ];

        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();

        // method
        // curl_setopt($ch, CURLOPT_URL, 'https://graph.facebook.com/v17.0/me/feed?message=sfjd%20fsjfs%20f&access_token=EAAC8B73OSYgBAEcQmDZCxztaGK8kGZAYaB8Wr1Oc1ze2q1I8NFnZAiYmoysqpGjZBu7bvSoqDcKMMBjO5xFjkoT3UISCqvWZCHZAx2sfuQgnixTblrzQJLIr9A29XnXMbDQ5BLQZCM0WjDE7RsMMJwa9lXDNGQiZC9dws9ZCxlBbpJmIedVPVjPZBZB');
        // curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        // curl_setopt($ch, CURLOPT_POST, 1);

        // $result = curl_exec($ch);
        // if (curl_errno($ch)) {
        //     echo 'Error:' . curl_error($ch);
        // }
        // curl_close($ch);
        // dd($result);

        try {
            // method
            $me = $fb->get('https://graph.facebook.com/me', $accessToken, "devesh", $graphVersion);
            $response = $fb->post('https://graph.facebook.com/v17.0/me/feed', $data, $accessToken, "devesh", $graphVersion);

            $graphNode = $response->getGraphUser();

            // Access user data
            $userId = $graphNode->getId();
            $userName = $graphNode->getName();

            $data = [
                'data' => $graphNode,
                'user_id' => $userId,
                'user_name' => $userName
            ];

            if (empty($result)) {
                return $this->responseError([], Response::HTTP_NO_CONTENT, "Something went wrong.");
            }


            // return  response()->json($graphNode . 'Post created successfully.');
            return $this->responseSuccess($graphNode, Response::HTTP_OK, "Post created successfully.");
        } catch (\Facebook\Exceptions\FacebookResponseException $e) {
            return 'Graph API Error: ' . $e->getMessage();
        } catch (\Facebook\Exceptions\FacebookSDKException $e) {
            return 'Facebook SDK Error: ' . $e->getMessage();
        }
    }

    public function get_access_token($app_id, $app_secret)
    {
        // $url = "https://graph.facebook.com/oauth/access_token?client_id=$app_id&client_secret=$app_secret&grant_type=client_credentials";

        // $response = file_get_contents($url);
        // $data = json_decode($response, true);
        // return $data["access_token"];


        // ---------  OR ----------


        $url = "https://graph.facebook.com/oauth/access_token?client_id=$app_id&client_secret=$app_secret&grant_type=client_credentials";

        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

        $response = curl_exec($ch);
        curl_close($ch);

        $token = json_decode($response)->access_token;

        return $token;
    }
}
